/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calculette;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author etienne
 */
public class CalculetteFrame extends javax.swing.JFrame
{
    /**
     * Opérateurs.
     */
    
    private static final String OP_ADDITION = "+",
                                OP_SUBSTRACTION = "-",
                                OP_DIVISION = "/",
                                OP_MULTIPLICATION = "*",
                                OP_MODULO = "%";
    
    
    /**
     * Opérateur courant.
     */
    
    private String operator = OP_ADDITION;
    
    
    /**
     * Contenu actuel de la calculette.
     */
    
    private Double result = 0d;
    
    
    /**
     * Creates new form CalculetteFrame
     */
    public CalculetteFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        calculationField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        buttonNumber0 = new javax.swing.JButton();
        buttonNumber9 = new javax.swing.JButton();
        buttonNumber8 = new javax.swing.JButton();
        buttonNumber7 = new javax.swing.JButton();
        buttonNumber6 = new javax.swing.JButton();
        buttonNumber4 = new javax.swing.JButton();
        buttonNumber5 = new javax.swing.JButton();
        buttonNumber3 = new javax.swing.JButton();
        buttonNumber1 = new javax.swing.JButton();
        buttonNumber2 = new javax.swing.JButton();
        buttonDivision = new javax.swing.JButton();
        buttonMultiply = new javax.swing.JButton();
        buttonMinus = new javax.swing.JButton();
        buttonPoint = new javax.swing.JButton();
        buttonPlus = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonPoint3 = new javax.swing.JButton();
        buttonEqual = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculette");
        setAlwaysOnTop(true);
        setResizable(false);

        calculationField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        buttonNumber0.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        buttonNumber0.setText("0");
        buttonNumber0.setBorder(null);
        buttonNumber0.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonNumber0.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonNumber0.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonNumber0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber0ActionPerformed(evt);
            }
        });

        buttonNumber9.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        buttonNumber9.setText("9");
        buttonNumber9.setBorder(null);
        buttonNumber9.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonNumber9.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonNumber9.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonNumber9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber9ActionPerformed(evt);
            }
        });

        buttonNumber8.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        buttonNumber8.setText("8");
        buttonNumber8.setBorder(null);
        buttonNumber8.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonNumber8.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonNumber8.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonNumber8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber8ActionPerformed(evt);
            }
        });

        buttonNumber7.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        buttonNumber7.setText("7");
        buttonNumber7.setBorder(null);
        buttonNumber7.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonNumber7.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonNumber7.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonNumber7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber7ActionPerformed(evt);
            }
        });

        buttonNumber6.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        buttonNumber6.setText("6");
        buttonNumber6.setBorder(null);
        buttonNumber6.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonNumber6.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonNumber6.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonNumber6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber6ActionPerformed(evt);
            }
        });

        buttonNumber4.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        buttonNumber4.setText("4");
        buttonNumber4.setBorder(null);
        buttonNumber4.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonNumber4.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonNumber4.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonNumber4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber4ActionPerformed(evt);
            }
        });

        buttonNumber5.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        buttonNumber5.setText("5");
        buttonNumber5.setBorder(null);
        buttonNumber5.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonNumber5.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonNumber5.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonNumber5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber5ActionPerformed(evt);
            }
        });

        buttonNumber3.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        buttonNumber3.setText("3");
        buttonNumber3.setBorder(null);
        buttonNumber3.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonNumber3.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonNumber3.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonNumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber3ActionPerformed(evt);
            }
        });

        buttonNumber1.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        buttonNumber1.setText("1");
        buttonNumber1.setBorder(null);
        buttonNumber1.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonNumber1.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonNumber1.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber1ActionPerformed(evt);
            }
        });

        buttonNumber2.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        buttonNumber2.setText("2");
        buttonNumber2.setBorder(null);
        buttonNumber2.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonNumber2.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonNumber2.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNumber2ActionPerformed(evt);
            }
        });

        buttonDivision.setBackground(new java.awt.Color(86, 90, 196));
        buttonDivision.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        buttonDivision.setText("÷");
        buttonDivision.setBorder(null);
        buttonDivision.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonDivision.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonDivision.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivisionActionPerformed(evt);
            }
        });

        buttonMultiply.setBackground(new java.awt.Color(86, 125, 196));
        buttonMultiply.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        buttonMultiply.setText("×");
        buttonMultiply.setBorder(null);
        buttonMultiply.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonMultiply.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonMultiply.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiplyActionPerformed(evt);
            }
        });

        buttonMinus.setBackground(new java.awt.Color(86, 146, 196));
        buttonMinus.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        buttonMinus.setText("-");
        buttonMinus.setBorder(null);
        buttonMinus.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonMinus.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonMinus.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMinusActionPerformed(evt);
            }
        });

        buttonPoint.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        buttonPoint.setText(".");
        buttonPoint.setBorder(null);
        buttonPoint.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonPoint.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonPoint.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPointActionPerformed(evt);
            }
        });

        buttonPlus.setBackground(new java.awt.Color(86, 170, 196));
        buttonPlus.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        buttonPlus.setText("+");
        buttonPlus.setBorder(null);
        buttonPlus.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonPlus.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonPlus.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlusActionPerformed(evt);
            }
        });

        buttonDelete.setBackground(new java.awt.Color(224, 93, 0));
        buttonDelete.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonDelete.setText("←");
        buttonDelete.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonDelete.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonDelete.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonPoint3.setBackground(new java.awt.Color(86, 186, 196));
        buttonPoint3.setText("%");
        buttonPoint3.setBorder(null);
        buttonPoint3.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonPoint3.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonPoint3.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonPoint3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPoint3ActionPerformed(evt);
            }
        });

        buttonEqual.setBackground(new java.awt.Color(48, 170, 41));
        buttonEqual.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        buttonEqual.setText("=");
        buttonEqual.setBorder(null);
        buttonEqual.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonEqual.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonEqual.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEqualActionPerformed(evt);
            }
        });

        buttonClear.setBackground(new java.awt.Color(198, 20, 20));
        buttonClear.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonClear.setForeground(new java.awt.Color(255, 255, 255));
        buttonClear.setText("C");
        buttonClear.setBorder(null);
        buttonClear.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonClear.setMinimumSize(new java.awt.Dimension(32, 32));
        buttonClear.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonNumber0, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(buttonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonPoint3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(buttonEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonNumber8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonNumber9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNumber9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNumber8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonNumber0, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonPoint3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(buttonDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(buttonClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        buttonDelete.getAccessibleContext().setAccessibleDescription("Effacer le caractère");
        buttonPoint3.getAccessibleContext().setAccessibleName("Modulo");
        buttonPoint3.getAccessibleContext().setAccessibleDescription("Reste de la division");
        buttonEqual.getAccessibleContext().setAccessibleDescription("Afficher le résultat");
        buttonClear.getAccessibleContext().setAccessibleName("Clear");
        buttonClear.getAccessibleContext().setAccessibleDescription("Effacer tout");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculationField)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calculationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNumber0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber0ActionPerformed
        addToCalculationField("0");
    }//GEN-LAST:event_buttonNumber0ActionPerformed

    private void buttonNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber1ActionPerformed
        addToCalculationField("1");
    }//GEN-LAST:event_buttonNumber1ActionPerformed

    private void buttonNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber2ActionPerformed
        addToCalculationField("2");
    }//GEN-LAST:event_buttonNumber2ActionPerformed

    private void buttonNumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber3ActionPerformed
        addToCalculationField("3");
    }//GEN-LAST:event_buttonNumber3ActionPerformed

    private void buttonNumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber4ActionPerformed
        addToCalculationField("4");
    }//GEN-LAST:event_buttonNumber4ActionPerformed

    private void buttonNumber5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber5ActionPerformed
        addToCalculationField("5");
    }//GEN-LAST:event_buttonNumber5ActionPerformed

    private void buttonNumber6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber6ActionPerformed
        addToCalculationField("6");
    }//GEN-LAST:event_buttonNumber6ActionPerformed

    private void buttonNumber7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber7ActionPerformed
        addToCalculationField("7");
    }//GEN-LAST:event_buttonNumber7ActionPerformed

    private void buttonNumber8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber8ActionPerformed
        addToCalculationField("8");
    }//GEN-LAST:event_buttonNumber8ActionPerformed

    private void buttonNumber9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNumber9ActionPerformed
        addToCalculationField("9");
    }//GEN-LAST:event_buttonNumber9ActionPerformed

    private void buttonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPointActionPerformed
        addToCalculationField(".");
    }//GEN-LAST:event_buttonPointActionPerformed

    private void buttonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEqualActionPerformed
        try
        {
            Double content = Double.parseDouble(calculationField.getText());
            
            switch (operator)
            {
                case OP_DIVISION:
                    result /= content;
                    break;
                
                case OP_MODULO:
                    result %= content;
                    break;
                    
                case OP_MULTIPLICATION:
                    result *= content;
                    break;
                    
                case OP_SUBSTRACTION:
                    result -= content;
                    break;
                    
                default:
                case OP_ADDITION:
                    result += content;
            }
            
            calculationField.setText(result.toString());
            result = 0d;
        }
        catch (NullPointerException e)
        {
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Ce nombre n'est pas d'un format valide.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonEqualActionPerformed

    private void buttonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivisionActionPerformed
        changeOperator(OP_DIVISION);
    }//GEN-LAST:event_buttonDivisionActionPerformed

    private void buttonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiplyActionPerformed
        changeOperator(OP_MULTIPLICATION);
    }//GEN-LAST:event_buttonMultiplyActionPerformed

    private void buttonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMinusActionPerformed
        changeOperator(OP_SUBSTRACTION);
    }//GEN-LAST:event_buttonMinusActionPerformed

    private void buttonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlusActionPerformed
        changeOperator(OP_ADDITION);
    }//GEN-LAST:event_buttonPlusActionPerformed

    private void buttonPoint3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPoint3ActionPerformed
        changeOperator(OP_MODULO);
    }//GEN-LAST:event_buttonPoint3ActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        result = 0d;
        operator = OP_ADDITION;
        calculationField.setText("");
    }//GEN-LAST:event_buttonClearActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        if (! calculationField.getText().isEmpty())
            calculationField.setText("" + calculationField.getText().subSequence(0, calculationField.getText().length() - 1));
    }//GEN-LAST:event_buttonDeleteActionPerformed
    
    
    /**
     * Changement d'opérateur.
     */
    
    private void changeOperator(String operator)
    {
        try
        {
            Double content = Double.parseDouble(calculationField.getText());
            result = content;
            calculationField.setText("");
            
            this.operator = operator;
        }
        catch (NullPointerException e)
        {
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Ce nombre n'est pas d'un format valide.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    /**
     * Traitement du contenu du champ de texte.
     */
    
    private void addToCalculationField(String x)
    {
        String text = calculationField.getText();
        
        if (x.equals("."))
        {
            if (! text.matches("^.*\\..*$"))
            {
                calculationField.setText(text + ".");
            }
        }
        else if ( x.matches("^[0-9]$"))
        {
            calculationField.setText(text + x);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculetteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculetteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculetteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculetteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CalculetteFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonDivision;
    private javax.swing.JButton buttonEqual;
    private javax.swing.JButton buttonMinus;
    private javax.swing.JButton buttonMultiply;
    private javax.swing.JButton buttonNumber0;
    private javax.swing.JButton buttonNumber1;
    private javax.swing.JButton buttonNumber2;
    private javax.swing.JButton buttonNumber3;
    private javax.swing.JButton buttonNumber4;
    private javax.swing.JButton buttonNumber5;
    private javax.swing.JButton buttonNumber6;
    private javax.swing.JButton buttonNumber7;
    private javax.swing.JButton buttonNumber8;
    private javax.swing.JButton buttonNumber9;
    private javax.swing.JButton buttonPlus;
    private javax.swing.JButton buttonPoint;
    private javax.swing.JButton buttonPoint3;
    private javax.swing.JTextField calculationField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
